--PREPARCIAL BASE DE DATOS SQL
CREATE DATABASE (
    ALMACEN_FEDE
);

CREATE TABLE PRODUCTOS (
    PRO_ID NUMBER NOT NULL, 
    PRO_NOMBRE VARCHAR (250),
    PRO_UDM_ID NUMBER, 
    PRO_PRECIOS_ID NUMBER
);

ALTER TABLE PRODUCTOS(
    ADD CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO_ID)
    FOREIGN KEY PRO_UDM_ID REFERENCES UNIDADES_DE_MEDIDAS
);

CREATE TABLE STOCKS (
    STO_ID NUMBER NOT NULL,
    STO_CANTIDAD NUMBER, 
    STO_PRO_ID NUMBER
);

ALTER TABLE STOCKS (
    ADD CONSTRAINT PK_STO_ID PRIMARY KEY (STO_ID)
    FOREIGN KEY STO_PRO_ID REFERENCES PRODUCTOS
);

CREATE TABLE UNIDADES_DE_MEDIDAS(
    UDM_ID NUMBER NOT NULL, 
    UDM_NOMBRE VARCHAR (250)
);

ALTER TABLE UNIDADES_DE_MEDIDAS(
    ADD CONSTRAINT PK_UDM_ID PRIMARY KEY(UDM_ID)
);

INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_UDM_ID, PRO_PRECIOS)
            VALUES  (1, 'Harina', 2, '$4500')

INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_UDM_ID, PRO_PRECIOS)
            VALUES  (2, 'Pan Rallado', 2, '$4500')

INSERT INTO UNIDADES_DE_MEDIDAS (UDM_ID, UDM_NOMBRE)
            VALUES  (2, 'Kilogramos')

INSERT INTO UNIDADES_DE_MEDIDAS (UDM_ID, UDM_NOMBRE)
            VALUES  (3, 'Gramos')

-- Suma los valores de la columna PRO_PRECIOS
SELECT SUM(PRO_PRECIOS) AS Total
FROM PRODUCTOS
Total 9000

--Cuenta la cantidad de productos  de la tabla PRODUCTOS
SELECT COUNT (PRO_ID) AS Total_De_Productos
FROM PRODUCTOS 
Total_De_Productos 2